### ISSUE TITLE
t/abstractions.t fails (with Mail::Internet 2.17?)

### ISSUE THREAD

**Issue by eserte** [rjbs/Email-Abstract#9] opened 2016-05-14 12:28 UTC
My smokers started to report the following failure:
```
# testing Email::Simple with 2.210
# testing Mail::Internet with 2.17

#   Failed test 'correct stringification of Mail::Internet; same as reference object'
#   at t/lib/Test/EmailAbstract.pm line 74.
#          got: ''
#     expected: 'Joanna, All
# 
# Thanks. I got the following response from Fred Tydeman.
# 
# On Nov 13,  9:56am in "Re: Defect in XBD lr", Joanna Farley wrote:
# > Sun's expert in this area after some discussions with a colleague
# > outside of Sun concluded that for lround, to align with both C99 and SUS
# > changes of the following form were necessary:
# > this line of text is really long and no one need worry about it but why was such a long text chosen to begin with i mean really??
# 
# -----
# Andrew Josey                                The Open Group  
# Austin Group Chair                          Apex Plaza,Forbury Road,
# Email: a.josey@opengroup.org                Reading,Berks.RG1 1AX,England
# Tel:   +44 118 9508311 ext 2250             Fax: +44 118 9500110'

#   Failed test 'correct body length for Mail::Internet'
#   at t/lib/Test/EmailAbstract.pm line 80.
#          got: '0'
#     expected: '749'

#   Failed test 'correct stringification of Mail::Internet; same as reference object'
#   at t/lib/Test/EmailAbstract.pm line 74.
#          got: ''
#     expected: 'Joanna, All
# 
# Thanks. I got the following response from Fred Tydeman.
# 
# On Nov 13,  9:56am in "Re: Defect in XBD lr", Joanna Farley wrote:
# > Sun's expert in this area after some discussions with a colleague
# > outside of Sun concluded that for lround, to align with both C99 and SUS
# > changes of the following form were necessary:
# > this line of text is really long and no one need worry about it but why was such a long text chosen to begin with i mean really??
# 
# -----
# Andrew Josey                                The Open Group  
# Austin Group Chair                          Apex Plaza,Forbury Road,
# Email: a.josey@opengroup.org                Reading,Berks.RG1 1AX,England
# Tel:   +44 118 9508311 ext 2250             Fax: +44 118 9500110'

#   Failed test 'correct body length for Mail::Internet'
#   at t/lib/Test/EmailAbstract.pm line 80.
#          got: '0'
#     expected: '749'

#   Failed test 'correct stringification of Mail::Internet; same as reference object'
#   at t/lib/Test/EmailAbstract.pm line 74.
#          got: ''
#     expected: 'Joanna, All
# 
# Thanks. I got the following response from Fred Tydeman.
# 
# On Nov 13,  9:56am in "Re: Defect in XBD lr", Joanna Farley wrote:
# > Sun's expert in this area after some discussions with a colleague
# > outside of Sun concluded that for lround, to align with both C99 and SUS
# > changes of the following form were necessary:
# > this line of text is really long and no one need worry about it but why was such a long text chosen to begin with i mean really??
# 
# -----
# Andrew Josey                                The Open Group  
# Austin Group Chair                          Apex Plaza,Forbury Road,
# Email: a.josey@opengroup.org                Reading,Berks.RG1 1AX,England
# Tel:   +44 118 9508311 ext 2250             Fax: +44 118 9500110'

#   Failed test 'correct body length for Mail::Internet'
#   at t/lib/Test/EmailAbstract.pm line 80.
#          got: '0'
#     expected: '749'
# Looks like you failed 6 tests of 165.
t/abstractions.t ....... 
Dubious, test returned 6 (wstat 1536, 0x600)
Failed 6/165 subtests 
	(less 71 skipped subtests: 88 okay)
```
This seems to happen with the latest Mail::Internet (FYI @markov2)

**Comment by rjbs** [comment] 2016-05-15 01:51
Thanks.  Earlier today I filed a ticket on MailTools asking whether Mark had any ideas.  I'll look into this more in the near future.

**Comment by ppisar** [comment] 2016-05-16 11:45
This issue looks like a duplicate of <https://github.com/rjbs/Email-Abstract/issues/7>.

**Comment by rjbs** [comment] 2016-08-06 18:21
This has been fixed by a patch I sent in to MailTools.

https://metacpan.org/changes/distribution/MailTools#L6

**Closed by rjbs** 2016-08-06 18:21 UTC
